[package]
name = "mk_repl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mk_interpreter = { path = "../mk_interpreter" }
mk_parser = { path = "../mk_parser" }
rustyline = "8.2.0"